### ISSUE TITLE
Can't import HTSeq with version 0.9.0

### ISSUE THREAD

**Issue by nwaring1** [simon-anders/htseq#36]
After updating to version 0.9.0, I get the following error when trying to import HTSeq:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/HTSeq/__init__.py", line 9, in <module>
    from _HTSeq import *
  File "__init__.pxd", line 155, in init HTSeq._HTSeq (src/_HTSeq.c:41483)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

**Comment by iosonofabio** [comment]
Hi,
thanks for reporting, what's your OS and architecture? Can you please try compiling from source?
Thx
Fabio

**Comment by nwaring1** [comment]
I'm running OS X 10.11.3
Here is the architecture: 
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Boot ROM Version:	MBP111.0138.B16
  SMC Version (system):	2.16f68
  Serial Number (system):	C02MV0LAFH01
  Hardware UUID:	19620B22-0ADD-51DE-B9B8-B2450FD74A44

Thank you,
Nick

**Comment by iosonofabio** [comment]
Can you please try installing from source? Chances are the binary is for an earlier OSX version... Thanks

**Comment by nwaring1** [comment]
I just installed from source, and it seems to be working now. Thanks for the help!

**Comment by iosonofabio** [comment]
It is strange that you couldn't install from the wheel, as Python wheels on OSX are expected to cover a wide range of OSX versions.

- Can you please figure out which version of XCode and/or the OSX SDK you are running?
- Can you please build a wheel from your system and upload it somewhere where I can download it and test it?

Thank you!

**Comment by iosonofabio** [comment]
No activity for a while... closing.
