### ISSUE TITLE
Install HTSeq with Conda on Windows

### ISSUE THREAD

**Issue by afDeathscythe** [simon-anders/htseq#55]
Hi is there any chance to install the new version on Windows:

If I execute this Statement:
pip install HTSeq

 in Anaconda prompt as Admin I get this Error Message:

Collecting HTSeq
  Using cached https://files.pythonhosted.org/packages/f8/87/85bc27f3d96ff4cd9144cbbfb5eb7573654edd0f6970f5c49d15a17e5d6f/HTSeq-0.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    Traceback (most recent call last):
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\dhg8103\AppData\Local\Temp\easy_install-nj3cyveq\pysam-0.14.1\setup.py", line 223, in <module>
      File "C:\Users\dhg8103\AppData\Local\Temp\easy_install-nj3cyveq\pysam-0.14.1\setup.py", line 69, in run_make_print_config
        # Update version from VERSION file into module
      File "D:\Anaconda\anaconda3\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "D:\Anaconda\anaconda3\lib\subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "D:\Anaconda\anaconda3\lib\subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "D:\Anaconda\anaconda3\lib\subprocess.py", line 997, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dhg8103\AppData\Local\Temp\pip-install-lcnym_i4\HTSeq\setup.py", line 200, in <module>
        **kwargs
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\dist.py", line 504, in fetch_build_eggs
        replace_conflicting=True,
      File "D:\Anaconda\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "D:\Anaconda\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "D:\Anaconda\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1069, in obtain
        return installer(requirement)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\dist.py", line 571, in fetch_build_egg
        return cmd.easy_install(req)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 884, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 1152, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\command\easy_install.py", line 1138, in run_setup
        run_setup(setup_script, args)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "D:\Anaconda\anaconda3\lib\contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "D:\Anaconda\anaconda3\lib\contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "D:\Anaconda\anaconda3\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\dhg8103\AppData\Local\Temp\easy_install-nj3cyveq\pysam-0.14.1\setup.py", line 223, in <module>
      File "C:\Users\dhg8103\AppData\Local\Temp\easy_install-nj3cyveq\pysam-0.14.1\setup.py", line 69, in run_make_print_config
        # Update version from VERSION file into module
      File "D:\Anaconda\anaconda3\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "D:\Anaconda\anaconda3\lib\subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "D:\Anaconda\anaconda3\lib\subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "D:\Anaconda\anaconda3\lib\subprocess.py", line 997, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    symlinking folders for python3
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None

I don't have any clue how set the specific symlinking folders for python3 (google solutions did not help me)

If I download the HTSeq-0.10.0.tar.gz and try to execute pip install setup.py (also in Anaconda Prompt) I get follwing error:

Collecting setup.py
  Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py

Thanks & Regards,

Marko

**Comment by afDeathscythe** [comment]
Hi Fabio,

thanks for replying. I am working with HTseq since 3 years now and I don't have time to investigate more on the windows issue to get it running there. I would be pleased to help and if find out something related to the known pysam issue I will let you know.
