### ISSUE TITLE
HTSeq error with dexseq_count.py and Python 3

### ISSUE THREAD

**Issue by mblue9** [simon-anders/htseq#59]
Hello,

I was trying to run DEXSeq count reads mode (dexseq_count.py) and found it fails if Python 3 is used but works with Python 2.7. I *think* the issue may be HTSeq-related so reporting it here. 

The error I got is below (using dexseq 1.24.0 with htseq 0.9.1). Others have reported a similar error here: https://support.bioconductor.org/p/106685/

`
Fatal error: Exit code 1 () Traceback (most recent call last): File "/usr/local/tools/_conda/envs/mulled-v1-683dc60555985982bcd77839627baa1ef503a6a15fb8cf27f5b492bbedd69ac4/bin/dexseq_count.py", line 98, in <module> features[f.iv] += f File "python3/src/HTSeq/_HTSeq.pyx", line 451, in HTSeq._HTSeq.ChromVector.__iadd__ File "python3/src/HTSeq/_HTSeq.pyx", line 466, in HTSeq._HTSeq.ChromVector.apply File "python3/src/HTSeq/_HTSeq.pyx", line 449, in HTSeq._HTSeq.ChromVector.__iadd__.addval TypeError: unhashable type: 'GenomicFeature'
`

**Comment by iosonofabio** [comment]
Please update htseq to the latest version first.

**Comment by mblue9** [comment]
@iosonofabio that was fast thanks for the quick reply!

I thought 0.9.1 is the latest version? latest release listed here: https://github.com/simon-anders/htseq/releases

**Comment by nsoranzo** [comment]
There is 0.10.0 on [PyPI](https://pypi.org/project/HTSeq/), which was not tagged on this repository.

**Comment by iosonofabio** [comment]
Is this still relevant or solved? I'll close tomorrow if no answer by then.

**Comment by mblue9** [comment]
Hi @iosonofabio it was fixed for DEXSeq in the DEXSeq bioconda package here: https://github.com/bioconda/bioconda-recipes/pull/9854, but I'm not sure if it's a still an issue for HTSeq.
