### ISSUE TITLE
StepVector.so Error Message

### ISSUE THREAD

**Issue by cwarden45** [simon-anders/htseq#8]
Hi,

I am trying to install htseq-count on an Ubuntu VM.

I get the following error message if I simply run `htseq-count` after install HTSeq:

```
Traceback (most recent call last):
  File "/usr/bin/htseq-count", line 3, in <module>
    import HTSeq.scripts.count
  File "/usr/lib/python2.7/site-packages/HTSeq/__init__.py", line 9, in <module>
    from _HTSeq import *
  File "_HTSeq.pyx", line 14, in init HTSeq._HTSeq (src/_HTSeq.c:34537)
  File "/usr/lib/python2.7/site-packages/HTSeq/StepVector.py", line 26, in <module>
    _StepVector = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/HTSeq/StepVector.py", line 22, in swig_import_helper
    _mod = imp.load_module('_StepVector', fp, pathname, description)
ImportError: /usr/lib/python2.7/site-packages/HTSeq/_StepVector.so: undefined symbol: _ZNSt12out_of_rangeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

I have tried the following installation strategies:

1) `pip install htseq` (error message above)
2) install from PyPI source (error message above)
3) install from git code (error message: **gcc: error: src/_HTSeq.c: No such file or directory**)

I've tried uninstalling and re-installing numpy, and I've also tried installing htseq as root.  When installing from source, I've tried installing for all users and just myself (and I also get the same error if I try `python setup.py build' and I test the htseq-count in the 'build' folder).

Can you please help me troubleshoot?

Thanks,
Charles

**Comment by cwarden45** [comment]
Closing this issue because I was able to get HT-Seq to work within Docker
