### ISSUE TITLE
Conda install doesn't appear to work 

### ISSUE THREAD

**Issue by j-berg** [simon-anders/htseq#84]
I installed a couple versions of HTSeq from conda and keep getting this confusing error:

```
 htseq-count -h
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/.local/bin/htseq-count", line 4, in <module>
    __import__('pkg_resources').run_script('HTSeq==0.11.0', 'htseq-count')
  File "/uufs/chpc.utah.edu/common/home/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/uufs/chpc.utah.edu/common/home/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/uufs/chpc.utah.edu/common/home/anaconda3/lib/python3.6/site-packages/HTSeq-0.11.0-py3.6-linux-x86_64.egg-info/scripts/htseq-count", line 3, in <module>
    import HTSeq.scripts.count
  File "/uufs/chpc.utah.edu/common/home/anaconda3/lib/python3.6/site-packages/HTSeq/__init__.py", line 13, in <module>
    from HTSeq._HTSeq import *
  File "/uufs/chpc.utah.edu/common/home/anaconda3/lib/python3.6/site-packages/HTSeq/_HTSeq.py", line 7, in <module>
    __bootstrap__()
  File "/uufs/chpc.utah.edu/common/home/anaconda3/lib/python3.6/site-packages/HTSeq/_HTSeq.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
ImportError: dynamic module does not define init function (init_HTSeq)
```

Do you all have any ideas what the origin of this issue might be. I have been using HTSeq for a while and have never run into the issue until this clean install.

**Comment by j-berg** [comment]
It appears for some reason my conda install wasn't being directly pointed to, thus the issues. Working just fine now.
