### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by soerenwolfers** [simon-anders/htseq#93]
Fresh install of Ubuntu 18.04, Python 3.7 (Anaconda). Running `pip install HTSeq` gives

```
Collecting HTSeq
  Downloading https://files.pythonhosted.org/packages/b1/55/3612dc17fe2a85c9f0a4b98b97aa8a9850d0930e2ad89deaf9c5e1271e97/HTSeq-0.11.2.tar.gz (611kB)
     |████████████████████████████████| 614kB 4.4MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/soeren/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v287k15b/HTSeq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v287k15b/HTSeq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-v287k15b/HTSeq/
    Complete output (227 lines):
    symlinking folders for python3
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: (sysconfig) CC=gcc -pthread -B /home/soeren/anaconda3/compiler_compat -Wl,--sysroot=/
    # pysam: (sysconfig) CFLAGS=-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
    # pysam: (sysconfig) LDFLAGS=-L/home/soeren/anaconda3/lib -Wl,-rpath=/home/soeren/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/
    checking for gcc... gcc -pthread -B /home/soeren/anaconda3/compiler_compat -Wl,--sysroot=/
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc -pthread -B /home/soeren/anaconda3/compiler_compat -Wl,--sysroot=/ accepts -g... yes
    checking for gcc -pthread -B /home/soeren/anaconda3/compiler_compat -Wl,--sysroot=/ option to accept ISO C89... none needed
    checking for ranlib... ranlib
    checking for grep that handles long lines and -e... /bin/grep
    checking for C compiler warning flags... unknown
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for _LARGEFILE_SOURCE value needed for large files... no
    checking shared library type for unknown-Linux... plain .so
    checking how to run the C preprocessor... gcc -pthread -B /home/soeren/anaconda3/compiler_compat -Wl,--sysroot=/ -E
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for stdlib.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for sys/param.h... yes
    checking for getpagesize... yes
    checking for working mmap... yes
    checking for gmtime_r... yes
    checking for fsync... yes
    checking for drand48... yes
    checking whether fdatasync is declared... yes
    checking for fdatasync... yes
    checking for library containing log... -lm
    checking for zlib.h... yes
    checking for inflate in -lz... yes
    checking for library containing recv... none required
    checking for bzlib.h... yes
    checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
    checking for lzma.h... yes
    checking for lzma_easy_buffer_encode in -llzma... yes
    checking for libdeflate.h... no
    checking for libdeflate_deflate_compress in -ldeflate... no
    checking for curl_easy_pause in -lcurl... yes
    checking for CCHmac... no
    checking for library containing HMAC... -lcrypto
    checking whether PTHREAD_MUTEX_RECURSIVE is declared... yes
    configure: creating ./config.status
    config.status: creating config.mk
    config.status: creating htslib.pc.tmp
    config.status: creating config.h
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    package init file 'samtools/__init__.py' not found (or not a regular file)
    package init file 'bcftools/__init__.py' not found (or not a regular file)
    package init file 'samtools/win32/__init__.py' not found (or not a regular file)
    package init file 'htslib/__init__.py' not found (or not a regular file)
    package init file 'htslib/htslib/__init__.py' not found (or not a regular file)
    warning: no files found matching 'KNOWN_BUGS'
    warning: no files found matching 'THANKS'
    no previously-included directories found matching 'tests/'
    warning: no files found matching 'samtools/configure'
    warning: no files found matching 'samtools/config.mk.in'
    warning: no files found matching 'samtools/config.h.in'
    htslib/hfile_libcurl.c:45:10: fatal error: curl/curl.h: No such file or directory
     #include <curl/curl.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    /home/soeren/anaconda3/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/easy_install-ki3cqlc6/pysam-0.15.3/pysam/libchtslib.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    Traceback (most recent call last):
      File "/home/soeren/anaconda3/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/soeren/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/soeren/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
        self.run_command(cmdname)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/home/soeren/anaconda3/lib/python3.7/distutils/command/install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "/home/soeren/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "/tmp/easy_install-ki3cqlc6/pysam-0.15.3/cy_build.py", line 86, in build_extension
      File "/home/soeren/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ki3cqlc6/pysam-0.15.3/setup.py", line 457, in <module>
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/home/soeren/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/soeren/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ki3cqlc6/pysam-0.15.3/setup.py", line 457, in <module>
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/soeren/anaconda3/lib/python3.7/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v287k15b/HTSeq/setup.py", line 200, in <module>
        **kwargs
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 720, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 787, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/soeren/anaconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    # pysam: htslib configure options: --enable-libcurl
    # pysam: htslib_config LIBHTS_OBJS=kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o hfile_libcurl.o hfile_gcs.o hfile_s3.o
    # pysam: htslib_config LIBS=-llzma -lbz2 -lz -lm -lcurl -lcrypto
    # pysam: htslib_config PLATFORM=default
    # pysam: config_option: ENABLE_PLUGINS=0
    # pysam: config_option: HAVE_COMMONCRYPTO=0
    # pysam: config_option: HAVE_GMTIME_R=1
    # pysam: config_option: HAVE_HMAC=1
    # pysam: config_option: HAVE_IRODS=0
    # pysam: config_option: HAVE_LIBCURL=1
    # pysam: config_option: HAVE_MMAP=1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by soerenwolfers** [comment]
Solution:
```
sudo apt install libcurl4-openssl-dev
sudo apt install libssl-dev
```

**Comment by simon-anders** [comment]
Thanks for answering your own question ;-)
